name: Test Docker Action
on:
  push:
    branches: main
    paths: [hello-world-docker-action/**]
  workflow_dispatch:
jobs:
  call-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: riz332

      - name: Output time set in the container
        run: echo "The time was ${{ teps.hello-action.outputs.time }} when the action said hello"
