name: Reuse other workflow
on:
  workflow_dispatch:
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: "riz332"
    
  use-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - name: Output from another workflow
        run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}
